{% set name = "behave" %}
{% set version = "1.3.0" %}
{% set sha256 = "b32ec1a1ed67f23adc007c1cb7ee31ac1c939638d30c8e3e27a00d9ddb063c09" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - behave = behave.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools <58   # because of https://github.com/behave/behave/issues/955 which will be released with 1.2.7
    - pip
  run:
    - python >={{ python_min }}
    - parse >=1.8.2
    - parse_type >=0.4.2
    - six >=1.11

test:
  imports:
    - behave
    - behave.compat
    - behave.formatter
    - behave.reporter
  requires:
    - python {{ python_min }}
  commands:
    - behave --help

about:
  home: https://github.com/behave/behave
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'behave is behaviour-driven development, Python style'
  description: |
    Behavior-driven development (or BDD) is an agile software development
    technique that encourages collaboration between developers, QA and
    non-technical or business participants in a software project.

    behave uses tests written in a natural language style, backed up by Python
    code.
  doc_url: https://behave.readthedocs.io
  dev_url: https://github.com/behave/behave

extra:
  recipe-maintainers:
    - stuertz
