{% set name = "behave" %}
{% set version = "1.2.6" %}
{% set sha256 = "b9662327aa53294c1351b0a9c369093ccec1d21026f050c3bd9b3e5cccf81a86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1005
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - behave = behave.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools <58   # because of https://github.com/behave/behave/issues/955
                       # which will be released with 1.2.7
    - pip
  run:
    - python >={{ python_min }}
    - parse >=1.6.3
    - parse_type >=0.3.4
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - behave
    - behave.compat
    - behave.formatter
    - behave.reporter

  commands:
    - behave --help

about:
  home: http://github.com/behave/behave
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'behave is behaviour-driven development, Python style'
  description: |
    Behavior-driven development (or BDD) is an agile software development
    technique that encourages collaboration between developers, QA and
    non-technical or business participants in a software project.

    behave uses tests written in a natural language style, backed up by Python
    code.
  doc_url: http://pythonhosted.org/behave/
  dev_url: http://github.com/behave/behave

extra:
  recipe-maintainers:
    - stuertz
