{% set name = "behave" %}
{% set version = "1.3.1" %}
{% set sha256 = "2a1f3a2490242132c4daf0732d9b65c99be6fef1f787f97fd028ea5a402025ff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - behave = behave.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools <58   # because of https://github.com/behave/behave/issues/955 which will be released with 1.2.7
    - pip
  run:
    - python >={{ python_min }}
    - parse >=1.18.0
    - parse_type >=0.6.0
    - six >=1.15
    - cucumber-tag-expressions >=4.1.0

test:
  imports:
    - behave
    - behave.compat
    - behave.formatter
    - behave.reporter
  requires:
    - python {{ python_min }}
  commands:
    - behave --help

about:
  home: https://github.com/behave/behave
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'behave is behaviour-driven development, Python style'
  description: |
    Behavior-driven development (or BDD) is an agile software development
    technique that encourages collaboration between developers, QA and
    non-technical or business participants in a software project.

    behave uses tests written in a natural language style, backed up by Python
    code.
  doc_url: https://behave.readthedocs.io
  dev_url: https://github.com/behave/behave

extra:
  recipe-maintainers:
    - stuertz
