# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: behave
  version: "1.3.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/behave-${{ version }}.tar.gz
  sha256: a1ef97c9e05ca4c19e60302d07ee1092480d2632c2e96abb30bb69a08b1681fb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - behave = behave.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - cucumber-tag-expressions >=4.1.0
    - cucumber-expressions >=17.1.0
    - parse >=1.18.0
    - parse_type >=0.6.0
    - six >=1.15.0
    - colorama >=0.3.7
    - tomli >=1.1.0
    # Keep the package noarch but allow for the win only dep
    - if: linux
      then:
        - __linux
    - if: osx
      then:
        - __osx
    - if: win
      then:
        - __win
        - win_unicode_console

tests:
  - python:
      imports:
        - behave
        - behave.compat
        - behave.formatter
        - behave.reporter
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - behave --help

about:
  homepage: https://github.com/behave/behave
  summary: behave is behaviour-driven development, Python style
  license: BSD-2-Clause
  license_file: LICENSE
  description: |
    Behavior-driven development (or BDD) is an agile software development
    technique that encourages collaboration between developers, QA and
    non-technical or business participants in a software project.

    behave uses tests written in a natural language style, backed up by Python
    code.
  documentation: https://behave.readthedocs.io
  repository: https://github.com/behave/behave

extra:
  recipe-maintainers:
    - rxm7706
    - stuertz
